config/routes.rb
Colinandjessionrails::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'party/:id' => 'parties#show'
  get 'party' => 'parties#index', as: 'party'

  match "/rsvp" => redirect("/rsvps/new")
  match "/rsvps" => redirect("/rsvps/new")

  resource :story, :registry, :noog, :wedding
  resources :rsvps
  resources :directions, only: [:index]
  resources :hotels, only: [:index]

  root to: "home#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :rsvp
  validates_presence_of :first_name, :last_name
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  belongs_to :rsvp
end

app/models/partier.rb
class Partier < ActiveRecord::Base
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  has_many :guests
  has_many :kids
  accepts_nested_attributes_for :guests, :kids

  validates_inclusion_of :can_attend, :in => [true, false]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render 'index.html', layout: false}
    end
  end
end

app/controllers/noogs_controller.rb
class NoogsController < ApplicationController
  def show
    respond_to do |format|
      format.html
      format.json { render 'show.html', layout: false}
    end
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
    @bridesmaids = Partier.find :all, conditions: {bridesmaid: true}
    @groomsmen = Partier.find :all, conditions: {bridesmaid: false}
    respond_to do |format|
      format.html
      format.json { render 'index.html', layout: false}
    end
  end

  def show
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def new
    @rsvp = Rsvp.new(params[:rsvp])
    @adult_count = params[:adult_count] ? params[:adult_count].to_i : 2
    @children_count = params[:children_count] ? params[:children_count].to_i : 0
    @adult_count.times { @rsvp.guests.build }
    @children_count.times { @rsvp.kids.build }
    respond_to do |format|
      format.html
      format.json { render 'new.html', layout: false}
    end
  end

  def create
    rsvp = params[:rsvp]
    rsvp['guests_attributes'].delete_if { |k, v| v['first_name'].empty? && v['last_name'].empty? }
    rsvp['kids_attributes'].delete_if { |k, v| v['first_name'].empty? && v['last_name'].empty? } if rsvp['kids_attributes']
    @rsvp = Rsvp.new(rsvp)
    @rsvp.name = @rsvp.guests.first.last_name unless @rsvp.guests.empty?
    @adult_count = params[:adult_count] ? params[:adult_count].to_i : 2
    @children_count = params[:children_count] ? params[:children_count].to_i : 0
    unless @rsvp.save
       render :new
    end
  end

  def show
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/noog_helper.rb
module NoogHelper
end

app/helpers/party_helper.rb
module PartyHelper
end

app/helpers/registry_helper.rb
module RegistryHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")/
    %meta(http-equiv="X-UA-Compatible" content="IE=edge,chrome=1")/
    %title Jessi and Colin
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")/
    %meta(name="description" content="Jessi Peterson and Colin Rymer are getting married on 9/8/12 in Chattanooga, TN!")/
    %meta(name="author" content="Colin Rymer")/

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #container
      %header
        %h1#logo Jessi &amp; Colin
        %nav
          %ul
            %li=link_to "Home", root_path
            %li=link_to "Story", story_path
            %li=link_to "Wedding", wedding_path
            %Li=link_to "Registry", registry_path
            %li=link_to "RSVP", new_rsvp_path
            %li=link_to "Wedding Party", party_path
            %li=link_to "Accommodations", hotels_path
            %li=link_to "&rsquo;Noog".html_safe, noog_path
            %li=link_to "Directions", directions_path
      %section
        = yield
      #container_footer
    %footer#footer
      %p Built by Colin Rymer. &copy; 2012